### ISSUE TITLE
virtualbox client is broken 

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/jumpscaleX_libs#173]
Needed for this issue https://github.com/threefoldtech/home/issues/635

![image](https://user-images.githubusercontent.com/41957921/79691360-4fc47300-825f-11ea-831f-6872f31d9f90.png)

**Comment by waleedhammam** [comment]
It's because virtualbox is not installed

install on linux using 

```bash
sudo add-apt-repository multiverse && sudo apt-get update
sudo apt install virtualbox
virtualbox
```

![Screenshot from 2020-05-07 15-56-00](https://user-images.githubusercontent.com/10658229/81303005-6c441600-907b-11ea-9f65-c4f74a4b903d.png)

**Comment by rkhamis** [comment]
perhaps an install method? @waleedhammam

**Comment by waleedhammam** [comment]
@rkhamis this client is for the insystem only. and may some os like windows or mac don't support cli installation, or the version ?

**Comment by rkhamis** [comment]
no no. you're right.

**Comment by Pishoy** [comment]
when try to install jsx in host ubuntu it fail as below 
```
root@jsxbishoy:~# ./3sdk_v10.5.3_linux_x86_64 --expert
3sdk> install
..........
python3-pip is already the newest version (9.0.1-2.3~ubuntu1.18.04.1).
The following packages were automatically installed and are no longer required:
  bridge-utils grub-pc-bin libdumbnet1 ubuntu-fan
Use 'apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Requirement already satisfied: pudb in /usr/local/lib/python3.6/dist-packages
Requirement already satisfied: pygments>=1.0 in /usr/local/lib/python3.6/dist-packages (from pudb)
Requirement already satisfied: urwid>=1.1.1 in /usr/local/lib/python3.6/dist-packages (from pudb)
OK
Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 11, in <module>
    from softwareproperties.SoftwareProperties import SoftwareProperties, shortcut_handler
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 67, in <module>
    from gi.repository import Gio
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 42, in <module>
    from . import _gi
ImportError: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/_MEI5QOVEd/libgirepository-1.0.so.1)

Could not execute:    apt-get update
    apt-get upgrade -y --force-yes
    apt-get install sudo python3-pip  -y
    pip3 install pudb
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
    apt-get update
    sudo apt-get install docker-ce -y


3sdk> 
```


-  note sure why jsx not install , is it need a ubuntu desktop ?
```
root@jsxbishoy:~# cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.4 LTS"
root@jsxbishoy:~# 
```

**Comment by m-motawea** [comment]
installer error should be in another issue however it is fixed here 
https://github.com/threefoldtech/jumpscaleX_core/pull/864

**Comment by Pishoy** [comment]
verified
```
3BOTDEVEL:jsxbishoy:jumpscaleX_libs: git log -1
commit 7513ec400d0c60353486fc971880a9b81abb188a (HEAD -> master, tag: v10.5.3, origin/master)
Merge: 41a8062 6d75496
Author: Reem Khamis <khamisr@codescalers.com>
Date:   Thu May 14 16:54:24 2020 +0200

    Merge pull request #213 from threefoldtech/rc_10.5.3
    
    Fixes in zosv2 sal regarding gw

```
