### ISSUE TITLE
j.sal.ubuntu issues 

### ISSUE THREAD

**Issue by Pishoy** [threefoldtech/jumpscaleX_libs#5]
1 - issue with  `j.sal.ubuntu.deb_download_install` ,can not download and install due this method contains a method called `j.sal.nettools.download` which is configured improperly , error as below 
 
![image](https://user-images.githubusercontent.com/21987477/64609454-415ed080-d3cd-11e9-817d-c577c3c9a02c.png)

2 - issue with `j.sal.ubuntu.service_install` , can not install a package as below error 
```
JSX> j.sal.ubuntu.service_install('apache2','/etc/init.d')                                                                                                                                                  
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/sandbox/lib/jumpscale/JumpscaleLibs/sal/ubuntu/Ubuntu.py", line 228, in service_install
    cmd = j.dirs.replace_txt_dir_vars(cmd)
AttributeError: 'Dirs' object has no attribute 'replace_txt_dir_vars'

'Dirs' object has no attribute 'replace_txt_dir_vars'
JSX>  
```
3 - issue with method `.apt_sources_list()` , does not show sources 
```
JSX> j.sal.ubuntu.apt_sources_list()                                                                                                                                                                        
<aptsources.sourceslist.SourcesList object at 0x7f1dba8f9550>

```

**Comment by serboctor** [comment]
Fixed by https://github.com/threefoldtech/jumpscaleX_libs/commit/7e1e9b6c280db127fda76d7ff67b45c99919b966, https://github.com/threefoldtech/jumpscaleX_libs/commit/a39898926e4d6331358c9e93732226a891afbd3a, and https://github.com/threefoldtech/jumpscaleX_libs/commit/f9037784cb78e7ef598ba85a9145f3c914279202

**Comment by Pishoy** [comment]
issue 1 , 3 are verified
issue 2, need enhancement to check the service existing before create a config file also not works with jsx installed in system as systemd is default not initctl command , error as below 
```
JSX> j.sal.ubuntu.service_install('mysqltest','/etc/init.d')                                                                                  
/bin/bash: initctl: command not found
Tue 01 08:16:01 core/InstallTools.py -2255 - execute                            : EXCEPTION: 

    Could not execute: 'initctl reload-configuration'stderr:
        /bin/bash: initctl: command not found
--TRACEBACK------------------
<stdin> in <module>
    1    
/sandbox/lib/jumpscale/JumpscaleLibs/sal/ubuntu/Ubuntu.py in service_install
    237    j.sal.process.execute("initctl reload-configuration", useShell=True)
/sandbox/lib/jumpscale/Jumpscale/sal/process/SystemProcess.py in execute
    110    retry=retry,
 ```

**Comment by Pishoy** [comment]
also there is issue with apt_get_cache_keys method as below:
```
JSX> j.sal.ubuntu.apt_get_cache_keys()                                                                                                        
Tue 01 11:54:32 sal/ubuntu/Ubuntu.py - 343 - apt_get_cache_keys                 : EXCEPTION: 
    AttributeError("'NoneType' object has no attribute 'keys'",)
--TRACEBACK------------------
<stdin> in <module>
    1    
/sandbox/lib/jumpscale/JumpscaleLibs/sal/ubuntu/Ubuntu.py in apt_get_cache_keys
    343    return list(self._cache_ubuntu.keys())
-----------------------------

'NoneType' object has no attribute 'keys'
JSX>  

```

**Comment by serboctor** [comment]
commit https://github.com/threefoldtech/jumpscaleX_libs/commit/a340417caca341897a7a78779409c91b1551cbd3 for fixing `apt_get_cache_keys` and for checking that the service exists.

**Comment by Pishoy** [comment]
verified
```
 JSX> j.sal.ubuntu.service_install('mysqltest','/etc/init.d')                                                                                                                                                
Wed 02 09:32:18 sal/ubuntu/Ubuntu.py - 222 - service_install                    : EXCEPTION: 
    Service daemon doesn't exist: /etc/init.d/mysqltest
--TRACEBACK------------------
<stdin> in <module>
    1    
/sandbox/lib/jumpscale/JumpscaleLibs/sal/ubuntu/Ubuntu.py in service_install
    222    raise j.exceptions.Value("Service daemon doesn't exist: %s" % service_path)
-----------------------------
```

**Comment by Pishoy** [comment]
sorry, forgot issue of initctl  
```JSX> j.sal.ubuntu.service_install('mysql','/etc/init.d')                                                                                  
/bin/bash: initctl: command not found
Tue 01 08:16:01 core/InstallTools.py -2255 - execute                            : EXCEPTION: 

    Could not execute: 'initctl reload-configuration'stderr:
        /bin/bash: initctl: command not found
--TRACEBACK------------------
<stdin> in <module>
    1    
/sandbox/lib/jumpscale/JumpscaleLibs/sal/ubuntu/Ubuntu.py in service_install
    237    j.sal.process.execute("initctl reload-configuration", useShell=True)
/sandbox/lib/jumpscale/Jumpscale/sal/process/SystemProcess.py in execute
    110    retry=retry,
```
- ubuntu version is `Ubuntu 18.04.3 LTS` insystem

**Comment by Pishoy** [comment]
- another issue is about  method `service_status` does not return a bool (True or False), it return None incase JSX installed insystem
it compare output with sentence `"%s is running"` and `"%s is not running"` --> this output does not exist incase insystem installation as insystem installation is using systemd so the output will not like above will be like ` Active: active (running) ` incase service running 

https://github.com/threefoldtech/jumpscaleX_libs/blob/development/JumpscaleLibs/sal/ubuntu/Ubuntu.py#L292

**Comment by serboctor** [comment]
I refactored the sal to check the pid 1 process, if it is systemd, it will use systemd, if it is my_init, it will use my init, otherwise it will raise an error. All service functions have been refactored accordingly.

**Comment by Pishoy** [comment]
verified 
```
JSX> j.sal.ubuntu.service_status('cron')                                                                                                                                                                    
● cron.service - Regular background program processing daemon
   Loaded: loaded (/lib/systemd/system/cron.service; disabled; vendor preset: enabled)
   Active: inactive (dead)
     Docs: man:cron(8)

Oct 10 11:17:24 testwikis systemd[1]: /etc/systemd/system/cron.service:10: Invalid environment assignment, ignoring: None
Oct 10 11:17:24 testwikis systemd[1]: cron.service: Current command vanished from the unit file, execution of the command list won't be resumed.
Oct 10 11:17:24 testwikis systemd[1]: /etc/systemd/system/cron.service:10: Invalid environment assignment, ignoring: None
Oct 10 11:17:25 testwikis systemd[1]: /etc/systemd/system/cron.service:10: Invalid environment assignment, ignoring: None
Oct 10 11:17:25 testwikis systemd[1]: /etc/systemd/system/cron.service:10: Invalid environment assignment, ignoring: None
Oct 10 11:17:25 testwikis systemd[1]: Stopping cron...
Oct 10 11:17:25 testwikis systemd[1]: Stopped cron.
Oct 10 11:17:25 testwikis systemd[1]: /etc/systemd/system/cron.service:10: Invalid environment assignment, ignoring: None
Oct 10 11:17:25 testwikis systemd[1]: /etc/systemd/system/cron.service:10: Invalid environment assignment, ignoring: None
Oct 10 11:17:25 testwikis systemd[1]: /etc/systemd/system/cron.service:10: Invalid environment assignment, ignoring: None
False

JSX> j.sal.ubuntu.service_start('cron')                                                                                                                                                                     
● cron.service - Regular background program processing daemon
   Loaded: loaded (/lib/systemd/system/cron.service; disabled; vendor preset: enabled)
   Active: inactive (dead)
     Docs: man:cron(8)

Oct 10 11:17:24 testwikis systemd[1]: /etc/systemd/system/cron.service:10: Invalid environment assignment, ignoring: None
Oct 10 11:17:24 testwikis systemd[1]: cron.service: Current command vanished from the unit file, execution of the command list won't be resumed.
Oct 10 11:17:24 testwikis systemd[1]: /etc/systemd/system/cron.service:10: Invalid environment assignment, ignoring: None
Oct 10 11:17:25 testwikis systemd[1]: /etc/systemd/system/cron.service:10: Invalid environment assignment, ignoring: None
Oct 10 11:17:25 testwikis systemd[1]: /etc/systemd/system/cron.service:10: Invalid environment assignment, ignoring: None
Oct 10 11:17:25 testwikis systemd[1]: Stopping cron...
Oct 10 11:17:25 testwikis systemd[1]: Stopped cron.
Oct 10 11:17:25 testwikis systemd[1]: /etc/systemd/system/cron.service:10: Invalid environment assignment, ignoring: None
Oct 10 11:17:25 testwikis systemd[1]: /etc/systemd/system/cron.service:10: Invalid environment assignment, ignoring: None
Oct 10 11:17:25 testwikis systemd[1]: /etc/systemd/system/cron.service:10: Invalid environment assignment, ignoring: None
(0, '', '')

JSX> j.sal.ubuntu.service_status('cron')                                                                                                                                                                    
● cron.service - Regular background program processing daemon
   Loaded: loaded (/lib/systemd/system/cron.service; disabled; vendor preset: enabled)
   Active: active (running) since Thu 2019-10-10 11:22:14 UTC; 5s ago
     Docs: man:cron(8)
 Main PID: 25543 (cron)
    Tasks: 1 (limit: 2361)
   CGroup: /system.slice/cron.service
           └─25543 /usr/sbin/cron -f

Oct 10 11:22:14 testwikis systemd[1]: Started Regular background program processing daemon.
Oct 10 11:22:14 testwikis cron[25543]: (CRON) INFO (pidfile fd = 3)
Oct 10 11:22:14 testwikis cron[25543]: (CRON) INFO (Skipping @reboot jobs -- not system startup)
True

JSX> j.sal.ubuntu.service_status('cron') 

```
 - jsx version 
```
commit a394ab7f256c39d65b5037496a2c881ea9fa1953 (HEAD -> development, origin/development, origin/HEAD)
Author: Ahmed T. Youssef <xmonader@gmail.com>
Date:   Thu Oct 10 12:56:28 2019 +0200

    use alias for SPA
```
